### ISSUE TITLE
Pip install the package. It couldn't support flask v1.0

### ISSUE THREAD

**Issue by shilinlee** [rantav/flask-restful-swagger#118] opened 2018-05-04 10:37 UTC
You should replace
 `from flask.ext.restful import Resource, fields`
 with
 ` from flask_restful import Resource, fields` 
in
  `/site-packages/flask_restful_swagger/swagger.py", line 14, in <module>`.

Please fix it.

**Comment by shilinlee** [comment] 2018-05-04 12:28
Please fix the package in Pypi.

**Comment by Koff** [comment] 2018-05-13 15:39
Why not create a Pull Request with this, instead of ordering a fix from someone else?
Just my two cents.

**Comment by theMarix** [comment] 2018-05-13 17:09
The issue is already fixed on master. What needs to be done is a release and publishing the new release on PyPI. Neither of this can be done via a PR but only by the package maintainer.

**Comment by sijis** [comment] 2018-05-23 18:38
@sobolevn @rantav @niall-byrne Is it possible to have a new release on PyPI that includes the `flask.ext` fixes from https://github.com/rantav/flask-restful-swagger/pull/107.

**Comment by niall-byrne** [comment] 2018-06-09 17:46
I've created a PR, and have messaged @rantav about this.  I have been inactive as the maintainer for sometime, but would be interested in getting involved again.

**Comment by niall-byrne** [comment] 2018-06-10 18:45
I have created release https://github.com/niall-byrne/flask-restful-swagger/releases/tag/0.20 to solve this issue.  Please verify and I will close this issue, and move onto the next highest priority task.

**Comment by niall-byrne** [comment] 2018-06-10 19:16
To ensure we set the flask version correctly, I also upgraded the dependency version for flask-restful.
Please reference [this](https://github.com/niall-byrne/flask-restful-swagger/releases/tag/0.20.1) release.

**Comment by shilinlee** [comment] 2018-06-11 09:05
OK. Thanks!!! Please close the issue.

**Closed** 2018-06-11 12:36 UTC
Labels: Needs Validation

**Comment by sijis** [comment] 2018-06-11 15:10
@niall-byrne Thank you so much for working through this and releasing a new version.
